--- 
- !ruby/object:SystemSettings 
  attributes: 
    session_expired_page_id: "2"
    session_timeout: "7200"
    menu_depth: "3"
    site_default_page_id: "1"
    permission_denied_page_id: "4"
    id: "1"
    not_found_page_id: "3"
    default_markup_style_id: "1"
    public_role_id: "1"
    footer_message: A <a href="http://goldberg.rubyforge.org">Goldberg</a> site
    site_name: Goldberg
    site_subtitle: A website development tool for Ruby on Rails
